export enum CmsFarmFormColumnDisplayType {
  TEXT = 'TEXT',
  TEXTAREA = 'TEXTAREA',
  SELECT = 'SELECT',
  RADIO = 'RADIO',
  CHECKBOX = 'CHECKBOX',
  DATE = 'DATE',
  GALLERY = 'GALLERY',
  EDITOR = 'EDITOR',
  HTMLEDITOR = 'HTMLEDITOR',
  DATETIME = 'DATETIME',
  TREE = 'TREE',
  LABEL = 'LABEL',
  CUSTOM = 'CUSTOM',
  LINK = 'LINK',
}

export enum CmsFarmTableColumnDisplayType {
  LABEL = 'LABEL',
  LINK = 'LINK',
}

export enum CmsFarmFormColumnTriggerType {
  DATATRIGGER = 'DATATRIGGER',
  ENABLETRIGGER = 'ENABLETRIGGER',
  READONLYTRIGGER = 'READONLYTRIGGER',
  REQUIREDTRIGGER = 'REQUIREDTRIGGER',
}

export enum CmsFarmTableDataAction {
  CREATE = 'CREATE',
  MODIFY = 'MODIFY',
  DELETE = 'DELETE',
  PREVIEW = 'PREVIEW',
  AUDITING = 'AUDITING',
  DETAIL = 'DETAIL',
  PUBLISH = 'PUBLISH',
}
