@startuml

Title Farm : data flow
actor user
participant "CmsFarmDataResolver" as dataProviderRouter << service >>
participant "DynamicRoutingComponent" as dynamicComp << component >>
participant "FarmSharedService" as farmSharedService << service >>
participant "FarmSharedContainerModalComponent" as dataProviderModal << component >>
participant "FarmService" as farmService << service >>
participant "FarmSharedComponent" as main << component >>

==enter func by router==
user -> dataProviderRouter: funcId
note left: 透過 menu 路由進入 Farm
dataProviderRouter -> farmService: getFarmByFuncID()
activate farmService
return FarmInfoGetResponseModel
dataProviderRouter -> dynamicComp: routing => activatedRoute.data.farm
dynamicComp -> dynamicComp : ActivatedRoute.data.subscribe()
dynamicComp -> main: input : FarmInfoGetResponseModel

==enter func by modal==
user -> farmSharedService: openFarm(funcID)
note left: 透過 modal 外部開啟 Farm
farmSharedService -> dataProviderModal: funcId
dataProviderModal -> farmService: getFarmByFuncID()
activate farmService
return FarmInfoGetResponseModel
dataProviderModal -> main: input : FarmInfoGetResponseModel

@enduml