@startuml

Title Farm : presentation
participant "FarmSharedComponent" as main << component >>
participant "[child of FarmSharedComponent]\nFarmFormInfoComponent\n DetailInfo" as detailInfo << component >>
participant "[child of FarmSharedComponent]\nFarmFormInfoComponent\n SearchInfo" as searchInfo << component >>
participant "[child of FarmSharedComponent]\nFarmTableInfoComponent\n TableInfo" as tableInfo << component >>

main -> detailInfo: input farm.detailInfo
note right: FarmFormInfoModel
main -> searchInfo: input farm.category.searchInfo
note right: FarmFormInfoModel
main -> tableInfo: input farm.category.tableInfo
note right: FarmTableInfoModel

@enduml