@startuml
Title Farm : query table info

actor user
participant "FarmSharedComponent" as main << component >>
participant "[child of FarmSharedComponent]\nFarmFormInfoComponent\n DetailInfo" as detailInfo << component >>
participant "[child of FarmSharedComponent]\nFarmFormInfoComponent\n SearchInfo" as searchInfo << component >>
participant "[child of FarmSharedComponent]\nFarmTableInfoComponent\n TableInfo" as tableInfo << component >>
participant "FarmService" as farmService << service >>

==user interaction==
user -> main
note left: 按下 "查詢"
main -> main: queryData()
main -> main: resetTablePage()
note left: 重設當前page

user -> main
note left: 按下 "清除"
main -> main: clearSearchInfoAndQueryData()
main -> searchInfo: searchInfoComponent.clearForm()
note left: 清除表單
searchInfo -> searchInfo: clearForm()
main -> main: resetTablePage()
note left: 重設當前page

user -> tableInfo
note left: 按下 "上下頁按鈕"
tableInfo -> tableInfo: pageChange.emit()
tableInfo --> main
note right: 通知按鈕觸發
main -> main: onTablePageChange()
note left: 收到通知

==query==
main -> main: getCategoryTableInfo()
main -> searchInfo: searchInfoComponent?.getFormInfo()
note left: 取得查詢條件
return FarmFormInfoModel

main -> farmService
note left: 查詢資料
activate farmService
return FarmTableInfoModel

main -> main: 帶回 category.tableInfo
note left: 套用資料

==presentation==

main -> tableInfo: input farm.category.tableInfo
note right: FarmTableInfoModel

@enduml