# This is a basic workflow to help you get started with Actions

name: CMSNpmPublishNext

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ npm-publish-github-actions ]
  pull_request:
    branches: [ npm-publish-github-actions ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build1:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'npm-publish-next') || contains(github.event.head_commit.message, 'npm-publish-latest')"


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # === 1. 根據 commit 做變數處理 ===
      - name: Set Variable from Commit
        env:
          IS_NEXT: ${{ contains(github.event.head_commit.message, 'npm-publish-next') }}
        run: |
          echo "task=cms-core/render" >> $GITHUB_ENV
          echo "package_json_path=." >> $GITHUB_ENV
          
          if ${IS_NEXT} == true; then
            echo "npm_version_tag=next" >> $GITHUB_ENV
            echo "npm_version_tag set to next"
          else
            echo "npm_version_tag=latest" >> $GITHUB_ENV
            echo "npm_version_tag set to latest"
          fi
      # ==============================


      # === 2. 顯示變數 ===
      - name: Show variable
        run: echo build1 task:${{env.task}}, npm_version_tag:${{env.npm_version_tag}}
      # ==================

  build2:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'npm-publish')"


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # === 2. 顯示變數 ===
      - name: Show variable
        run: echo build2
      # ==================

   
